### ISSUE TITLE
[Bug] comments in `rocks.toml` on inline configurations not handled properly

### ISSUE THREAD

**Issue by Quitlox** [nvim-neorocks/toml-edit.lua#35]
Hi there, thanks for the work on this project!

When you have a comment describing your inline plugin and call any rocks command that manipulates this configuration, the resulting `rocks.toml` is broken.

#### [Before] `rocks.toml`
```toml
[rocks]
[plugins]
"rocks.nvim" = "2.36.1"
"rocks-git.nvim" = "2.0.1"

# Test
"markdown.nvim" = { git = "meanderingprogrammer/markdown.nvim" }
```
#### Act
1. `Rocks update`

#### [After] `rocks.toml`
```toml
[rocks]
[plugins]
"rocks.nvim" = "2.36.1"
"rocks-git.nvim" = "2.0.1"

[
# Test
plugins."markdown.nvim" ]
git = "meanderingprogrammer/markdown.nvim"
rev = "v4.1.0^{}"
```
